services:
  - type: web
    name: deblurgan-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: DEBLURGAN_MAX_DIM
        value: "384"
